# Generated by Django 6.0.2 on 2026-05-18 23:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Privilegio_App', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory')], max_length=20, unique=True)),
                ('coat_margin', models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SizeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4)),
                ('measurement', models.CharField(choices=[('chest', 'Pecho'), ('waist', 'Cintura'), ('shoulders', 'Hombros'), ('neck', 'Cuello'), ('arm_length', 'Largo de brazo'), ('hips', 'Cadera'), ('leg_length', 'Largo de pierna'), ('thigh', 'Muslo'), ('total_length', 'Largo total')], max_length=20)),
                ('min_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('max_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Privilegio_App.categorysizechart')),
            ],
            options={
                'ordering': ['measurement', 'size'],
                'unique_together': {('chart', 'size', 'measurement')},
            },
        ),
    ]
